import Control from './Control';
import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by Geesun',
}

export default async function RootLayout({ children }) {

  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics");
  const topics = await resp.json();

  return (
    <html>
      <body>
      <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.map( t => {
            return <li key={t.id}><Link href={`/read/${t.id}`}>{t.title}</Link></li>
          })}
        </ol>
        {children}
          <Control/>
        
        </body>
    </html>
  )
}
